name: Publish preview build

on:
  push:
    branches: ['main']
    paths:
      - !**/*.md
    
jobs:
  publish_preview_update:
    name: Publish preview build
    type: build
    params:
      platform: android
      profile: preview
